server:
  port: 8180

spring:
  main:
    allow-bean-definition-overriding: true

zuul:
  routes:
    course:
      path: /course/**
#      url: http://127.0.0.1:8081/course/
      url: http://course-service:8081/course/
    user:
      path: /user/**
#      url: http://127.0.0.1:8082/user/
      url: http://user-service:8082/user/

