apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  ports:
  - port: 30001
    protocol: TCP
    targetPort: 8180
    nodePort: 30001
  selector:
    app: api-gateway
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: 192.168.56.102:8080/micro-service/api-gateway-zuul:latest
        ports:
        - containerPort: 8180
      imagePullSecrets:
        - name: regcred

