apiVersion: v1
kind: Service
metadata:
#  labels:
#    app: message-service
  name: message-service
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: message-service
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: message-service-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: message-service
    spec:
      containers:
      - name: message-service
        image: 192.168.56.102:8080/micro-service/message-thrift-python-service:latest
        ports:
        - containerPort: 9090
      imagePullSecrets:
      - name: regcred

